language: node_js  #设置语言

node_js: "lts/*"  #设置相应的版本

install:
  - npm install  #安装hexo及插件

before_script:
  - cd themes/Level6
  - npm install
  - npm run build
  - cd ../..
script:
  - hexo cl  #清除
  - hexo g  #生成

cache:
  npm: true
  directories:
    - node_modules
    
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  keep_history: true
  skip_cleanup: true
  local_dir: public
  fqdn: aphage.me
  on:
    branch: master