language: node_js

node_js: "lts/*"

install:
  - npm install

before_script:

script:
  - hexo build

cache:
  npm: true
  directories:
    - node_modules
    
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  keep_history: true
  skip_cleanup: true
  local_dir: public
  fqdn: aphage.me
  on:
    branch: master